### ISSUE TITLE
"View Logs" number of lines back should be configurable

### ISSUE THREAD

**Issue by seidnerj** [homebridge/homebridge-config-ui-x#1473]
### Feature Description

Currently the "View Logs" page only shows the last 50,000 bytes of the HomeBridge log. This is very confusing as this is not indicated anywhere in this screen. I suggest 3 changes:

1. Move from readying last X number of bytes to reading last X number of lines.
2. Allowing the user configure how many lines back this screen should read (or set to "unlimited", essentially reading the entire log)
3. At the top of the page, it should be indicated how lines were read going back from the end of the log (if there was indeed a limit set), i.e. instead of the top of the page looking like this:
```
Loading logs using native method...
File: /var/lib/homebridge/homebridge.log
```

It should look something like this:

```
Loading the last 50,000 lines from logs using native method...
File: /var/lib/homebridge/homebridge.log
```

If no limit was set it should look something like this:
```
Loading all lines from logs using native method...
File: /var/lib/homebridge/homebridge.log
```

**Comment by andrewk123** [comment]
I'm not sure that this would be good payback for the devs time since all of that (and more) can be done from the built-in terminal (today) with a few simple commands:

Just opening the terminal from the "three dot" menu will get you a terminal window in the the correct directory (in my case /var/lib/homebridge)

`cat homebridge.log | tail -n 50000 `

will then give you the last 50000 lines in the log.

Perhaps more usefully, you could also search for log messages on a specific date such as:

`cat homebridge.log | grep -a '3/25/2023'`

That will give you all the log entries from 3/25/2023 (the format of the date inside the quotes will depend on the locale of your system).

or the following will give you the last 10 log messages that have the word 'Error' in them.

`cat homebridge.log | grep -a 'Error' |  tail -n 10`

Personally I would prefer the devs time to go towards things we can't easily do for ourselves (YMMV).
